// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1xHq85fQnnpeshPCs6boo3VJr5rW-fBs',
    appId: '1:254821518092:web:5617c06a6aa34cb8a69729',
    messagingSenderId: '254821518092',
    projectId: 'limeapp-34c6f',
    authDomain: 'limeapp-34c6f.firebaseapp.com',
    storageBucket: 'limeapp-34c6f.firebasestorage.app',
    measurementId: 'G-51BEP30TLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkkP9vhhP3psVKOjcJRqe_YRyPR9RPFV8',
    appId: '1:254821518092:android:b2572be2fe70ed15a69729',
    messagingSenderId: '254821518092',
    projectId: 'limeapp-34c6f',
    storageBucket: 'limeapp-34c6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjN8xzGETZz6tmsueCBT0LmEXKrx60Zc0',
    appId: '1:254821518092:ios:57b5a8bbad2f055da69729',
    messagingSenderId: '254821518092',
    projectId: 'limeapp-34c6f',
    storageBucket: 'limeapp-34c6f.firebasestorage.app',
    iosBundleId: 'com.example.rsp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjN8xzGETZz6tmsueCBT0LmEXKrx60Zc0',
    appId: '1:254821518092:ios:57b5a8bbad2f055da69729',
    messagingSenderId: '254821518092',
    projectId: 'limeapp-34c6f',
    storageBucket: 'limeapp-34c6f.firebasestorage.app',
    iosBundleId: 'com.example.rsp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1xHq85fQnnpeshPCs6boo3VJr5rW-fBs',
    appId: '1:254821518092:web:b967028b46dcd6e8a69729',
    messagingSenderId: '254821518092',
    projectId: 'limeapp-34c6f',
    authDomain: 'limeapp-34c6f.firebaseapp.com',
    storageBucket: 'limeapp-34c6f.firebasestorage.app',
    measurementId: 'G-NR9CVEM07X',
  );

}